# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_1.ui'
#
# Created: Tue Jul 04 16:49:22 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(389, 542)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.figure2 = GraphicsView(self.centralwidget)
        self.figure2.setGeometry(QtCore.QRect(10, 40, 360, 120))
        self.figure2.setObjectName(_fromUtf8("figure2"))
        self.figure1 = PlotWidget(self.centralwidget)
        self.figure1.setGeometry(QtCore.QRect(10, 180, 360, 151))
        self.figure1.setObjectName(_fromUtf8("figure1"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 340, 361, 141))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sliderGain = QtGui.QSlider(self.gridLayoutWidget)
        self.sliderGain.setMaximumSize(QtCore.QSize(30, 160))
        self.sliderGain.setAutoFillBackground(False)
        self.sliderGain.setMaximum(255)
        self.sliderGain.setOrientation(QtCore.Qt.Vertical)
        self.sliderGain.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderGain.setTickInterval(50)
        self.sliderGain.setObjectName(_fromUtf8("sliderGain"))
        self.gridLayout.addWidget(self.sliderGain, 3, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.sliderBrigh = QtGui.QSlider(self.gridLayoutWidget)
        self.sliderBrigh.setMaximumSize(QtCore.QSize(30, 160))
        self.sliderBrigh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sliderBrigh.setAutoFillBackground(False)
        self.sliderBrigh.setMinimum(0)
        self.sliderBrigh.setMaximum(255)
        self.sliderBrigh.setOrientation(QtCore.Qt.Vertical)
        self.sliderBrigh.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderBrigh.setTickInterval(50)
        self.sliderBrigh.setObjectName(_fromUtf8("sliderBrigh"))
        self.gridLayout.addWidget(self.sliderBrigh, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.sliderContr = QtGui.QSlider(self.gridLayoutWidget)
        self.sliderContr.setMaximumSize(QtCore.QSize(30, 160))
        self.sliderContr.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.sliderContr.setAutoFillBackground(False)
        self.sliderContr.setMaximum(255)
        self.sliderContr.setOrientation(QtCore.Qt.Vertical)
        self.sliderContr.setInvertedAppearance(False)
        self.sliderContr.setInvertedControls(False)
        self.sliderContr.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderContr.setTickInterval(50)
        self.sliderContr.setObjectName(_fromUtf8("sliderContr"))
        self.gridLayout.addWidget(self.sliderContr, 3, 3, 1, 1)
        self.sliderWB = QtGui.QSlider(self.gridLayoutWidget)
        self.sliderWB.setMaximumSize(QtCore.QSize(30, 160))
        self.sliderWB.setAutoFillBackground(False)
        self.sliderWB.setMaximum(10000)
        self.sliderWB.setSingleStep(500)
        self.sliderWB.setPageStep(1000)
        self.sliderWB.setOrientation(QtCore.Qt.Vertical)
        self.sliderWB.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderWB.setTickInterval(1000)
        self.sliderWB.setObjectName(_fromUtf8("sliderWB"))
        self.gridLayout.addWidget(self.sliderWB, 3, 4, 1, 1)
        self.buttonStart = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonStart.setMaximumSize(QtCore.QSize(50, 16777215))
        self.buttonStart.setObjectName(_fromUtf8("buttonStart"))
        self.gridLayout.addWidget(self.buttonStart, 0, 0, 1, 1)
        self.buttonStop = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonStop.setMaximumSize(QtCore.QSize(50, 16777215))
        self.buttonStop.setObjectName(_fromUtf8("buttonStop"))
        self.gridLayout.addWidget(self.buttonStop, 0, 1, 1, 1)
        self.sliderExpo = QtGui.QSlider(self.gridLayoutWidget)
        self.sliderExpo.setMaximumSize(QtCore.QSize(30, 160))
        self.sliderExpo.setAutoFillBackground(False)
        self.sliderExpo.setMinimum(1)
        self.sliderExpo.setMaximum(7)
        self.sliderExpo.setOrientation(QtCore.Qt.Vertical)
        self.sliderExpo.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.sliderExpo.setTickInterval(1)
        self.sliderExpo.setObjectName(_fromUtf8("sliderExpo"))
        self.gridLayout.addWidget(self.sliderExpo, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 389, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Spectrometer v1.0", None))
        self.label_2.setText(_translate("MainWindow", "Expo", None))
        self.label.setText(_translate("MainWindow", "Gain", None))
        self.label_3.setText(_translate("MainWindow", "Bright.", None))
        self.label_4.setText(_translate("MainWindow", "Cont.", None))
        self.label_6.setText(_translate("MainWindow", "WB", None))
        self.buttonStart.setText(_translate("MainWindow", "Start", None))
        self.buttonStop.setText(_translate("MainWindow", "Stop", None))
        self.label_5.setText(_translate("MainWindow", "RGB Image", None))

from pyqtgraph import GraphicsView, PlotWidget

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

